### PR TITLE
feat: add support for token based auth

### LINKED ISSUE #24: Use Sonar Token instead of login/password
Hello,

I would try to use this pluggin to connect to my sonar server for which I am using token. Is it possible to use token instead of login/password ?
**exemple** : 
{
  "project": "adisreyaj_compito",
  "sonarURL": "https://sonarcloud.io",
  "auth": {
    "token": "fkqsfbsdkfn6789dlqsfsldnfsd",
  }
}
Thanks
FD

### PR DESCRIPTION
**Pull request by adisreyaj**

### CODE REVIEW

**Comment by lukzeg** [comment]
Hi @adisreyaj ,

Thanks for creating this update. Looks awesome and works. If I may propose to add as well additional in info under json file which you generate using template:
https://github.com/adisreyaj/vscode-sonarqube-status/blob/master/src/data/constants.ts#L1

That new token key is available?

What I have on mind is:

```
export const VSCODE_PROJECT_CONFIG = {
 _comment: 'The authentication can be proceed in two ways. Using combination of username and password or token. The project.json which contains two of them at once is invalid.'
  project: '<your-key-here>',
  sonarURL: '<your-sonar-url>',
  auth:
  {
    username: '<sonar-username>',
    password: '<sonar-password>',
    token: '<sonar-token>'
  }
};
```
To inform that user can select, either have token or username and password authentication.
It might be useful for people, which does not read README.md but they just look inside generate project.json file.

What do you think?

**Comment by adisreyaj** [comment]
> Hi @adisreyaj ,
> 
> Thanks for creating this update. Looks awesome and works. If I may propose to add as well additional in info under json file which you generate using template:
> https://github.com/adisreyaj/vscode-sonarqube-status/blob/master/src/data/constants.ts#L1
> 
> That new token key is available?
> 
> What I have on mind is:
> 
> ```
> export const VSCODE_PROJECT_CONFIG = {
>  _comment: 'The authentication can be proceed in two ways. Using combination of username and password or token. The project.json which contains two of them at once is invalid.'
>   project: '<your-key-here>',
>   sonarURL: '<your-sonar-url>',
>   auth:
>   {
>     username: '<sonar-username>',
>     password: '<sonar-password>',
>     token: '<sonar-token>'
>   }
> };
> ```
> To inform that user can select, either have token or username and password authentication.
> It might be useful for people, which does not read README.md but they just look inside generate project.json file.
> 
> What do you think?

Yeah. I do understand and the comment can help for sure.

In future, I can probably add a prompt to let user choose what auth they want to go with.

**Comment by lukzeg** [comment]
Hi @adisreyaj,

Any chances that your PR will be merged?

**Comment by adisreyaj** [comment]
> Hi @adisreyaj,
> 
> Any chances that your PR will be merged?

Soon...

**Pull request merged**
